module.exports = {
    es: {
        translation: {
            WELCOME_MESSAGE_1: "Veo que ya tenéis una partida empezada, decid 'recuperar partida' si queréis seguirla o 'empezar partida nueva' para comenzar otra. ",
            WELCOME_MESSAGE_2: "¡Bienvenidos! Comienza la aventura. Confío en que vosotros podréis salvar el planeta de todos los problemas medioambientales que están teniendo lugar. Vamos a comenzar una partida nueva, así que insertad el identificador en la aplicación móvil:<break time='1s'/>  %s. <break time='1s'/> ",
            WELCOME_REPROMPT_MESSAGE : "Me tenéis que decir el número de equipos para poder avanzar.",
            RECOVER_GAME_MESSAGE : "Perfecto, vamos a recuperar la partida con código: <break time='1s'/> %s. <break time='1s'/> Veamos en qué casilla estaba cada jugador, sus sellos ganados, y a quién le tocaba tirar el dado: <break time='1s'/>",
            HOW_MANY_PLAYERS_MESSAGE : "Recordad que un equipo no tiene máximo ni mínimo de personas que pueden formarlo, por tanto, ¿cuántos equipos van a participar en la misión?.",
            HOW_MANY_PLAYERS_REPROMPT_MESSAGE : "Me tenéis que decir el número de equipos para poder avanzar.", 
            TOO_MANY_PLAYERS_MESSAGE: 'El número de equipos debe ser menor que 4, por favor, decidme cuántos equipos vais a jugar. ',
            FEW_PLAYERS_MESSAGE: 'Para poder jugar debe registrarse más de un equipo. ¿Cuántos equipos vais a jugar?',
            START_REGISTRATION_MESSAGE: "Perfecto, comenzamos con el registro de los %s equipos. Como véis hay diferentes fichas, cada corona representa el color del equipo, ¿cuál es el color del primero?.",
            REPEAT_PLAYER_NAME_MESSAGE: "No he entendido bien, ¿podéis repetirlo?.", 
            PLAYER_TWO_REG_MESSAGE: "El equipo se ha registrado correctamente. ¿Podéis decirme el color del siguiente equipo?",
            PLAYER_THREE_REG_MESSAGE: "De acuerdo, pasamos al tercero.",
            PLAYER_FOUR_REG_MESSAGE: "Y por último pero no menos importante, ¿con qué color registramos al cuarto equipo?",
            NOT_VALID_TEAM_COLOUR: "El color indicado no pertenece a ningún equipo, por favor, elegid entre los siguientes: %s. Entonces, ¿cuál es el color del equipo?",
            ALL_PLAYERS_REG_MESSAGE: "El registro de equipos ha terminado. Los pequeños héroes van a ser: ",
            RANDOM_START_MESSAGE: " Va a comenzar la partida el %s. ",
            MOVE_PLAYER_MESSAGE: "%s, debéis moveros hasta la casilla %s.",
            ROLL_DICE_MESSAGE: " Así que ya podéis tirar el dado y así comenzar la aventura.<break time='4s'/>",
            NEXT_PLAYER_MESSAGE: ' %s es tu turno, tira el dado. <break time="4s"/>', 
            HOW_TO_ANSWER_MESSAGE: " Para responder hay que escanear la tarjeta correspondiente a la respuesta que consideramos que es la correcta y una vez hecho, podéis preguntarme si habéis acertado. Suerte!",
            DANTE_MESSAGE : ' Veo que os habéis cruzado con Dante. Este pequeñín, a parte de contaminar, se dedica a robar. Si no queréis que os robe uno de vuestros sellos, tendréis que responder correctamente a una pregunta de conocimiento la cual debéis escanear: ', 
            TRASH_MESSAGE : ' Nos hemos enterado de que habéis estado tirando basura por la calle y que además, os dejáis todas las luces de casa encendidas, por tanto, os vais a quedar un turno sin jugar para reflexionar y no volver a hacer todas esas cosas. ',
            SURPRISE_QUESTION_MESSAGE : ' Uno de los rivales escogerá una carta, ya sea del tipo acción o conocimiento, y debéis responder: ',
            CHANGE_OBJECTIVES_MESSAGE : ' Tenéis que intercambiar vuestra carta objetivo con la de otro jugador, cuando hayáis terminado, ', 
            CORRECT_ANSWER_MESSAGE: ' ¡Enhorabuena!, habéis acertado la pregunta.', 
            BAD_ANSWER_MESSAGE: ' Oh, lo siento. La respuesta es incorrecta. La respuesta correcta era la %s) %s ',
            WON_STAMP_MESSAGE: ' El sello que habéis ganado es: %s. ',
            CORRECT_SURPRISE_MESSAGE: ' ¡Enhorabuena!, podéis avanzar 3 casillas más. Dirigíos a la casilla %s. ',
            BAD_SURPRISE_MESSAGE: ' Esta vez no has acertado.. Debido a ello tienes que retroceder 2 casillas y dirigirte a la casilla %s. Aunque sea una casilla especial, tu turno ya ha terminado. ',
            CORRECT_DANTE_MESSAGE: 'Por esta vez os habéis librado, pero debeis andar con cuidado..', 
            BAD_STAMP_MESSAGE: 'Tenéis que darme un sello del tipo : %s. ', 
            BAD_NOSTAMP_MESSAGE: 'Al no acertar la respuesta íbamos a quitaros un sello, pero vemos que no tenéis ninguno. ',
            STEAL_SQUARE_MESSAGE: ' Vaya vaya.. el equipo situado a vuestra derecha puede robaros uno de vuestros sellos pero no se lo quedarán, ¿qué sello le quitamos al %s?. ',
            STEAL_STAMP: ' %s habéis perdido el sello de %s. ',
            STEAL_NO_STAMP : '%s no os han podido robar ya que no tenéis ningún sello de %s. ',
            LOSE_STAMP: ' Esta vez habéis tenido mala suerte, y habéis perdido un sello del tipo %s ', 
            WIN_STAMP: ' ¡Estáis de suerte!, acabáis de ganar un sello del tipo %s .', 
            NOTHING_HAPPENS: ' Se podría decir que no habéis tenido ni mala ni buena suerte, os quedáis tal y como estáis. ', 
            KNOWLEDGE_QUESTION: ' Toca responder a una pregunta de conocimiento, y como ya sabemos, si acertáis ganareis un sello. ', 
            GO_HOME: ' Madre mía, os toca volver a la casilla de salida, pero no pasa nada, aún no está todo perdido. ',
            LOST_TURN_MESSAGE : ' El %s no puede tirar. ',
            NOT_LOST_TURN_MESSAGE : 'puede tirar el dado el %s.', 
            COLORS_PRESENTATION : " Voy a presentar 3 colores: ", 
            CHOOSE_COLOR_EXPLANATION : ' Debéis escoger uno de ellos, pero cuidado, porque no todos esconden algo bueno. Cuando hayáis decidido debéis decir "He escogido el color .." y sabremos si ha sido o no una buena elección. ¡Que la suerte os acompañe!. ', 
            GET_KNOWLEDGE_QUESTION : ' Escoged una carta de conocimiento y escaneadla: <break time="5s"/> ', 
            GET_ACTION_QUESTION : ' Escoged una carta de acción y escaneadla: <break time="5s"/>', 
            NEUTRAL_SQUARE_MESSAGE : ' Como habéis caído en una casilla neutral, ',
            UNKNOWN_SQUARE_MESSAGE : 'Disculpad, no os he entendido bien, ¿en qué casilla habéis caído?' ,
            POS_BIGGER_THAN_ARRIVAL : ' Vaya, se os queda corto el tablero, quedaos en vuestra posición y probad suerte en el siguiente turno. ', 
            GOAL_ARRIVAL_MESSAGE : ' ¡Anda!, has llegado a la meta, escanea tu carta misión para ver si has ganado la partida y avisame cuando la tengas escaneada.',
            REPEAT_DICE_SCAN_MESSAGE : ' Parece que la carta no se ha escaneado bien, escanead de nuevo el dado y avisadme cuando hayáis tirado.',
            REPEAT_RESPONSE_SCAN_MESSAGE : ' Por favor, volved a escanear la respuesta escogida.',
            REMEMBER_CHOOSE_COLOR_MESSAGE : ' Por favor, elegid un color de los 3 dados y decidme cuál habéis elegido. ',
            LAST_SQUARE_MESSAGE : ' Vamos a ver cuántos sellos de cada tipo habéis conseguido durante la partida: ',
            NOT_LAST_SQUARE_MESSAGE : ' Creo que os habéis confundido, no estáis en la última casilla del juego, ¿podríais decirme en qué casilla estáis?. Si no es ninguna especial, pasa a ser el turno del %s y puede tirar el dado.',
            ZERO_STAMPS_MESSAGE : ' siento deciros que habéis llegado a la meta sin ningún sello, por lo que tendréis que volver a la casilla de salida y hacer el recorrido de nuevo. ',
            NO_STAMPS_TYPE_MESSAGE : ' No tenéis ningún sello de los tipos: ',
            STAMPS_TYPE_MESSAGE : '. Pero si habéis conseguido:',
            SCAN_MISSION_CART_MESSAGE : ' escanead vuestra carta mision. Avisadme cuando la carta esté escaneada',
            INCOMPLETE_MISSION_MESSAGE : 'Con los sellos obtenidos no se completa vuestra carta objetivo, volvéis a la casilla de salida. Debéis conseguir los que faltan ¡Ánimo! ',
            COMPLETE_MISSION_MESSAGE : 'Has ganado. Enhorabuena!',
            REPEAT_MISSION_SCAN_MESSAGE : 'Parece que la carta no se ha escaneado bien, escanead de nuevo la carta misión. Avisadme cuando esté escaneada',
            REPEAT_QUESTION_MESSAGE : 'La repito sin problema. ',
            REPEAT_DICE_MESSAGE : 'Habéis sacado un ',
            REPEAT_SQUARE_MESSAGE : 'Debéis dirigiros a la casilla ', 
            REPEAT_CARD_MESSAGE : 'La carta elegida no es del tipo correspondiente a la casilla en la que habéis caído, por favor, escanead una carta de %s .',
            SQUARE_TYPE_MESSAGE : ' Habéis caído en la casilla %s.',
            CHOOSEN_TEAM_COLOUR_MESSAGE : 'Este color ya ha sido elegido, elegid otro.',
            REPEAT_GAME_CODE_MESSAGE : 'El código de la partida es %s. <break time="4s"/>',
            REPEAT_PLAYER_TURN_MESSAGE : 'Le toca jugar al %s.',
        }  
    }
}
